server:
  extraFlags:
    - web.enable-lifecycle
    - web.enable-remote-write-receiver

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090
alertmanager:
  enabled: false
      
kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false
