apiVersion: 1

datasources:
  - name: Prometheus
    isDefault: true
    type: prometheus
    url: http://10.19.0.5:9090
    jsonData:
      httpMethod: GET
      timeInterval: 1m
  - name: Tempo
    isDefault: false
    type: tempo
    url: http://10.19.0.5:3100
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'Prometheus'
  - name: Loki
    isDefault: false
    type: loki
    url: http://10.19.0.5:8080
    jsonData:
      timeout: 60
      maxLines: 1000
      derivedFields:
        - datasourceName: Tempo
          matcherRegex: "TraceID=(\\w+)"
          name: TraceID
          url: '$${__value.raw}'
          datasourceUid: Tempo
